parameters:
- name: MAVEN_COMMON
  type: boolean
  default: false
- name: BUILD_TOOL
  type: string
  default: 'maven'
- name: MAVEN_VERSION
  type: string
- name: SNYK_DEBUG_ENABLED
  type: boolean
  default: false
- name: UNIT_TEST
  type: boolean
  default: false
- name: SNUNID
  type: string
  default: ''

steps:
- ${{ if eq(parameters.BUILD_TOOL, 'maven') }}:
  - task: Maven@3
    displayName: 'Build with Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      options: '-DskipTests=${{ not(parameters.UNIT_TEST) }}'
      mavenVersionOption: 'Version'
      mavenVersion: ${{ parameters.MAVEN_VERSION }}
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

- ${{ if eq(parameters.BUILD_TOOL, 'npm') }}:
  - script: |
      npm install
      npm run build
      npm test
    displayName: 'Build with NPM'
    condition: succeeded()

- script: |
    echo "##vso[build.addbuildtag]SNUNID-${{ parameters.SNUNID }}"
  displayName: 'Add SNUNID Tag'
  condition: and(succeeded(), ne(parameters.SNUNID, ''))

- task: PublishTestResults@2
  displayName: 'Publish Unit Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
  condition: always()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage'
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/target/site/jacoco/jacoco.xml'
    pathToSources: '$(Build.SourcesDirectory)'
  condition: always()
